# -*- coding: utf-8 -*-
"""arithmetic-operator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alePV3-fIRrAVuT0zt3hA9mssC78Myhf
"""

if __name__ == '__main__':
    a = int(raw_input())
    b = int(raw_input())

    print(a+b)
    print(a-b)
    print(a*b)