# -*- coding: utf-8 -*-
"""division.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alePV3-fIRrAVuT0zt3hA9mssC78Myhf
"""

from __future__ import division

if __name__ == '__main__':
    a = int(raw_input())
    b = int(raw_input())

    print(a//b)
    print(a/b)