# -*- coding: utf-8 -*-
"""if-else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alePV3-fIRrAVuT0zt3hA9mssC78Myhf
"""

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(raw_input())

    if n % 2 == 1:
        print "Weird"
    elif n % 2 == 0 and 2 <= n <= 5:
        print "Not Weird"
    elif n % 2 == 0 and 6 <= n <= 20:
        print "Weird"
    else:
        print "Not Weird"