# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alePV3-fIRrAVuT0zt3hA9mssC78Myhf
"""

if __name__ == '__main__':
    n = int(raw_input())

    for i in range(n):
        print(i*i)