# -*- coding: utf-8 -*-
"""print-func.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alePV3-fIRrAVuT0zt3hA9mssC78Myhf
"""

from __future__ import print_function

if __name__ == '__main__':
    n = int(raw_input())

    for i in range(1,n+1):
        print(i,end='')